course = "Python for Beginners"
print(course.upper())
print(course.lower())
print(course.find("p"))
print(course.find("P"))
print(course.find("f"))
print(course.find("Beginners"))
print(course.find("G"))
print(course.find("o"))
print(course.find("Python"))
print(course.lower())
print(course.upper())
print(course.replace("Python", "Nython"))
print(course.replace("o", "N"))
print(course.replace("n", "o"))
print(course.replace("P", "G"))
print(course.replace("for", "nor"))
print(course.replace("Beginers", "gg"))
print("P" in course)
print(course)